### ISSUE TITLE
Include option to exclude page from RSS feed

### ISSUE THREAD

**Issue by h-enk** [h-enk/hyas#5]
E.g. for thank you page after form submission:

```yaml
---
title: "Signed Up"
description: ""
date: 2019-11-22T20:14:45+01:00
draft: false
layout: page
images: [""]
robots: "noindex,noarchive"
feed_exclude: true
sitemap_exclude: true
---
```

Add custom `layouts/rss.xml`:

```xml
...
    {{ range .Pages }}{{ if ne .Params.feed_exclude true }}
    <item>
      <title>{{ .Title }}</title>
      <link>{{ .Permalink }}</link>
      <pubDate>{{ .Date.Format "Mon, 02 Jan 2006 15:04:05 -0700" | safeHTML }}</pubDate>
      {{ with .Site.Author.email }}<author>{{.}}{{ with $.Site.Author.name }} ({{.}}){{end}}</author>{{end}}
      <guid>{{ .Permalink }}</guid>
      <description>{{ .Summary | html }}</description>
    </item>
    {{ end }}{{ end }}
  </channel>
</rss>
```
